### PR TITLE
Kramdown

### PR DESCRIPTION
**Pull request by jedcn**
**UPDATE: I'm going to close this PR and make it so that all `.md` files are processed by `kramdown`. See https://github.com/jedcn/reveal-ck/pull/76 for details.**

# Overview

This change includes `kramdown` and sets it up to translate files ending in `*.kramdown`, such as `slides.kramdown`.

## Details

This was done to explore an answer for https://github.com/jedcn/reveal-ck/issues/71.

I didn't think this would work at first, but if you apply the same `pre`/`post` processing to kramdown as you do to redcarpet things up end up looking good.

## Replacing Redcarpet?

While I was doing this I looked into replacing the core markdown engine (redcarpet) with kramdown. It turns out that two things aren't supported:

1. Using the "```notes" extension to produce an `<aside class=notes">`, and
2. GFM Tables

I don't know how many people use #1 but it seems like it'd be a shame to drop #2.

## Plan

With that in mind, I think we'll go for supporting `slides.kramdown` as a kramdown file. I've verified that you can use `{.fragment}` to make ordered and unordered lists "fade in."

# To Do Before Releasing

* [ ] Verify that `{.fragment}` works as expected with a regular paragraph of text
* [ ] Configure kramdown to support GFM
* [ ] Cover important aspects of kramdown in a `.feature`-- lists, paragraphs, gfm tables, etc
* [ ] Work with @bertBruynooghe to determine if any parts of kramdown that should be verified
* [ ] Resolve issue where kramdown is producing `<p><code>...</code></p>` instead of `<pre><code>...</code></pre>` when doing code blocks.

### CODE REVIEW

**Comment by bertBruynooghe** [comment]
You write that GFM tables aren't supported in kramdown: is this by the way markdown is used, or is there another reason? When trying http://kramdown.herokuapp.com, I can see that GFM tables are working...

(will look into the other issues you mention above separately)

**Comment by bertBruynooghe** [comment]
You can use the `{:.fragment}` syntax also for regular text paragraphs too:

    {:.fragment}
    This is a regular paragraph.

(verified in http://kramdown.herokuapp.com/)

**Comment by jedcn** [comment]
If GFM are supported regularly then I misconfigured kramdown. I'll update the description of this PR with things I need to look into before releasing.

**Comment by gettalong** [comment]
kramdown's GFM parser supports tables as per the kramdown spec - see http://kramdown.gettalong.org/syntax.html#tables

**Comment by gettalong** [comment]
As for your todos:

* The syntax for attribute lists is `{: .class #id key="value"}`, so you missed the colon after the opening brace.

* You need to set `input: 'GFM'` so that the GFM parser is used and not the standard kramdown parser.

**Comment by bertBruynooghe** [comment]
mmm, I tried to use:

    gem "reveal-ck", git: 'https://github.com/jedcn/reveal-ck.git', ref: 'kramdown'

in my gemfile, and renamed my `slides.md` to `slides.kramdown` to see how the PR would affect my code, and now executing `bundle exec reveal-ck generate` gives me:

    Generating slides for 'slides.kramdown'..
    error: Don't know how to build task '/Users/bruynooghebert/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/reveal-ck-d5fe1dbfa2b9/files/reveal.js/css/reveal.css'

Any idea on this?

**Comment by jedcn** [comment]
When I create a release of `reveal-ck` I bundle up most of reveal.js into the gem.

However, I don't check reveal.js into source control-- instead it's put into the gem at build time (of the gem).

You've specified that you want to use `reveal-ck` from a particular git sha, but the reveal.js files aren't "checked in" at that sha.

I hope to be cutting a new release shortly-- kramdown replacing redcarpet is going pretty well-- but if I can't figure it out soon I'll cut two releases-- one that supports `slide.kramdown` and one that swaps in kramdown everywhere. Then you should be able to install from https://rubygems.com directly.

In the mean time, I think it will work if you:

0. Uninstall the reveal-ck you have right now
1. Clone reveal-ck to your local system
2. Step into that directory, check out the `kramdown` branch
3. Run a `bundle` and then run a `rake`. These two steps should pull down reveal.js and make sure the code in this directory is healthy

Then.. modify the `Gemfile` that you described above to reference reveal-ck by a local path.

Finally, repeat what you tried.

**Comment by bertBruynooghe** [comment]
Hi, I got my example working with the pull request, 
see how elegant a number of thing get (especially not having to escape code snippets anymore): https://gist.github.com/bertBruynooghe/8cc4bb982f62591e942ba917bf1119e6/revisions

I still do have some issues as text + code block in one fragment (not sure how to do this with kramdown), but generally speaking, it's a lot better for me.

I also discovered this nice one:

```
{:.fragment data-fragment-index="2"}
:skull: Don't do this:

~~~
<button class="btn">
~~~
{:.fragment data-fragment-index="1"}
```

and this one is nice too to allow markdown parsing inside a HTML block:

```
<div markdown="1" class="fragment">
Gemfile

    gem 'bootstrap-sass'
</div>
```

**Comment by jedcn** [comment]
I'm totally impressed by your slides. Nice work!

I'm going to swap out redcarpet for kramdown going forward.

I should be able to release https://github.com/jedcn/reveal-ck/pull/76 later tonight or tomorrow.

I'll publish a new version of the gem when I do this.

I'll add fragments from your slides into the `*.feature` files from cucumber/aruba.

Thanks for all of your input! I wasn't aware of kramdown or the `{:.fragment}` extension until you logged an issue. It definitely makes making slides funner and more powerful.

**Comment by jedcn** [comment]
Just about done with #76. Closing this now.

Before I leave this thread:

You can now use:

    ```
    code
    ```

In addition to:

    ~~~
    code
    ~~~

I had misconfigured kramdown before. This is fixed now.

Also-- You can use the ```notes shortcut that's part of reveal-ck to achieve something similar to what's above:

```notes
valid cases for ids:

1. as anchors to link to topics inside HTML
2. to bind labels to form fields => and even then, we could probably better wrap the fields inside a label ...

ids for tests? Bad practice.
```

**Pull request closed without merging**
