### PR TITLE
default output director to slide name

### PR DESCRIPTION
**Pull request by kbrock**
I was trying to share the problem I was running into in #52 but realized it would be easier to share as a diff.

I like the current output of the command that says "defaults to sample"

Not sure how to fix that. I guess adding in text into the description works, but want your input

### CODE REVIEW

**Comment by kbrock** [comment]
1. I don't need solution in particular merged, just want to share what got in my way.
2. Sorry I didn't think to submit a WIP instead of an issue. (don't want us to do double work)
3. The code has a number of bugs around naming the directory something other than `slides`. It is still hardcoded in places like the `Guardfile`
4. It would be nice to docuement how I could create my own `Guardfile`?
5. I've been using one slidedeck per repo and calling all of them slides.md due to the problems around using a directory name other than `slides`. So merging in this code will really bring out this problem.

**Comment by kbrock** [comment]
I was overthinking this.

Added features and fixed the `hump-day` example.
While I was at it, I matched the description text (google-...slides.md) with the actual test code.

**Comment by kbrock** [comment]
The docs in cucumber are great.
Added feature/documentation for the directory override.

Let me know if you want me to tweak anything or want to remove 'google' and go back to hump-day.

**Comment by jedcn** [comment]
Hah! I had forgotten all about [Hump day][youtube-hump-day]. It stems from when the 1 1/2 year old of some good friends laughed outrageously whenever she saw that commercial. And then ran around yelling hump day and laughing.

That said.. it's pretty odd without context. No need to go back.

I thought I'd be able to check in and make a release tonight, but that's looking unlikely. Will try again shortly.

[youtube-hump-day]: https://www.youtube.com/watch?v=RlFg-a1AJCU

**Comment by jedcn** [comment]
Hi! I just brought this into master! Thanks.

**Pull request closed without merging**
