### PR TITLE
Move emoji filter to own file

### PR DESCRIPTION
**Pull request by kbrock**
This belongs in it's own file

I'd also like to make other tweaks:

1. Rename to `ReveakCK::Builder::EmojiFilter`?
2. Ok to move `align='absmiddle'` to css?

Thoughts?

fyi jch/html-pipeline#195

### CODE REVIEW

**Comment by kbrock** [comment]
Interesting, `align='absmiddle'` is not consistent across browsers. [ref]

Some people implement with:
```css
img.emoji {
  display:table-cell;
  vertical-align:middle;
}
```
or
```css
img.emoji {
  margin-bottom:.25em;
  vertical-align:middle;
}
```

I did notice that `<small>x</small>` and `:emoji:` were not aligning correctly for me.

[ref]: http://stackoverflow.com/questions/2481120/absmiddle-works-differently-on-firefox-and-chrome

**Comment by jedcn** [comment]
Hi again!

Moving to its own file is a good idea-- not sure why I left it right there.

If it *is not* renamed, then it should live over at `./lib/html/pipeline`. But if it is renamed, this is a good resting place. I don't see any reason to *not* rename it, so long as it can still inherit from that base filter and everything (tests, rubocop) still passes.

Regarding CSS-- and `align="xxx"` moving out makes sense, right? If the styles aren't inlined then people will have more control, eh? If I recall correctly reveal-ck defines its own CSS [over in this file][reveal-ck.css].

[reveal-ck.css]: https://github.com/jedcn/reveal-ck/blob/master/files/reveal-ck/css/reveal-ck.css

---

I was going down this path (re: own file) over in this branch as I initially considered your request: https://github.com/jedcn/reveal-ck/compare/emoji-and-the-alts?expand=1. Which is to say-- lets add some tests as part of breaking it out (even if we don't change its behavior).

---

As for next steps, unless I hear objections / further activity, I will:

1. Merge this change and do the rename to `RevealCK::Builder::EmojiFilter`
2. Bring in the specs (for existing behavior-- not new) I wrote from the `emoji-and-the-alts` branch
3. We'll treat the CSS separately.

**Comment by kbrock** [comment]
Looking at all filters out there, they all keep in the correct namespace.

Don't like it, and a few issues over there are concerned about it.
But it seems like the way people are doing it.

**Comment by kbrock** [comment]
I agree this belongs over in html/pipeline/reveal_ck_emoji_fulter.
If you want me to move here, let me know, otherwise just close.

Your other branch does a better job w/ specs and all.

**Comment by jedcn** [comment]
Thanks. I took the commit you had here.. moved the file over to `lib/html/pipeline`, and added the specs from [emoji-and-the-alts][emoji-and-the-alts] (since that won't get merged now).

I included your commit (rather than just using the stuff from [emoji-and-the-alts][emoji-and-the-alts]) to make sure you ended up on the [contributors](https://github.com/jedcn/reveal-ck/graphs/contributors) page.

[emoji-and-the-alts]: https://github.com/jedcn/reveal-ck/tree/emoji-and-the-alts

**Comment by kbrock** [comment]
emoji filter has been changed. you may want to just overwrite `emoji_image_tag`

**Pull request merged**
